export const NEW_QUOTE_START = "NEW_QUOTE_START",
  NEW_QUOTE_SUCCESS = "NEW_QUOTE_SUCCESS",
  NEW_QUOTE_FAIL = "NEW_QUOTE_FAIL";

export const TOGGLE_FILTER = "TOGGLE_FILTER";

export const AUTH_START = "AUTH_START",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAIL = "AUTH_FAIL",
  AUTH_REFRESH_SUCCESS = "AUTH_REFRESH_SUCCESS",
  AUTH_REFRESH_FAIL = "AUTH_REFRESH_FAIL";

export const LOGOUT = "LOGOUT";

export const ADD_FAVORITE_START = "ADD_FAVORITE_START",
  ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS",
  ADD_FAVORITE_FAIL = "ADD_FAVORITE_FAIL";

export const DELETE_FAVORITE_START = "DELETE_FAVORITE_START",
  DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS",
  DELETE_FAVORITE_FAIL = "DELETE_FAVORITE_FAIL";

export const FETCH_FAVORITE_START = "FETCH_FAVORITE_START",
  FETCH_FAVORITE_SUCCESS = "FETCH_FAVORITE_SUCCESS",
  FETCH_FAVORITE_FAIL = "FETCH_FAVORITE_SUCCESS";

export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
